language: android
jdk: oraclejdk8
android:
  components:
    - tools

    # The BuildTools version used
    - build-tools-24.0.3

    # The SDK version used
    - android-25

    # Additional components
    - extra-android-m2repository
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash)