language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-m2repository
script:
  - ./gradlew build jacocoTestCoverage
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: lX3j0DNG126YSNG9HcKUZcCMVkLDXpugBCd57eTWcG4JFH+G3WGOiXXSCtQtzN9bUsSzKSRc9RgLNAowurj5ZH7QW5vuDpgGS02LTtiF31YA+j42cq39cZUcQOB/BCNqHXy5HCm1RdB4hPSdlnPIOnispY8tsGlPFCChdyRVE7cmGGAwHcOHwG8hVRnNacruLAaCbEq/TV5J7TdtHU6Mr/kr+wrTl2YKdSe7+2jcF/v9epr+x0fdTnA8xgagtcQUdkfhpVKXF3BfeWYsdazjDI735Fw8zD3X6jP/wLkFm1M27qZ7VC3egE4TR0DwAu3T6Rpy1aS28MfkEe2UvDWFMHlEwO3MiK2+9DiJCW91o9jsd3YV2eNHU2ubYj83PifqDt/3PZmarY/DGn7yKhOWQRjARal5xgffvgHPq0NLHo8mfZRvph3tm1pltBdIbk8lbv1z4RoMWOPTlqYWnnIHEyWtbuCea93x95w6+UIfyPJN/t5b3KBBZrU0KXuA83319aLk89JxKxf1Jy0uIOz3EfUQWwkaPWDk8RBgxjhQgOqA/qAdvvhJ7v8RzIwto7L+Kh3bJrXfhvpI0HjpwlE3yHGasZJz635uUXMbXE8pm8vRei0i+hEwJAAjNbEFYfamHIB3NhVjegZBAu2+3vVXMfLYL8dPoRVTWnXMgLb7UkM=
  file: neatle/build/outputs/aar/neatle-release.aar
  on:
    repo: InovaIT/neatle
    tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle