name: pull-request-build
run-name: "#${{ github.event.pull_request.number}} ${{ github.event.pull_request.title}}"
on: [pull_request]
jobs:
  build-app:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Compile lib
        run: "./gradlew assembleDebug assembleRelease"
      - name: Compile Unit Tests
        run: "./gradlew compileDebugUnitTestSources"
      - name: Run Unit Tests
        run: "./gradlew testDebug"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          comment_mode: failures
          junit_files: |
            **/build/outputs/*-results/**/*.xml
            **/build/*-results/**/*.xml
