name: publish
run-name: "#${{ github.event.pull_request.number}} ${{ github.event.pull_request.title}}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
jobs:
  build-app:
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    runs-on: "ubuntu-latest"
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Compile app
        run: "./gradlew assembleDebug assembleRelease"
      - name: Compile Unit Tests
        run: "./gradlew compileDebugUnitTestSources"
      - name: Run Unit Tests
        run: "./gradlew testDebug"
      - name: 'Create tag'
        run: 'git tag ${{ github.event.inputs.version }}'
      - name: 'Save GPG key'
        run: 'echo "${{ secrets.GPG_SIGNING_KEY }}" | base64 -d > neatle/signing_key.gpg'
      - name: 'Publish'
        run: './gradlew neatle:uploadArchives 
                -PossrhUsername=${{ secrets.OSSRH_USERNAME }} 
                -PossrhPassword=${{ secrets.OSSRH_PASSWORD }} 
                -Psigning.secretKeyRingFile=signing_key.gpg 
                -Psigning.password=${{ secrets.GPG_SIGNING_PASSPHRASE }} 
                -Psigning.keyId=${{ secrets.GPG_SIGNING_ID }}'
      - name: 'Push tag'
        run: 'git push ${{ github.event.inputs.version }}'
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          comment_mode: failures
          junit_files: |
            **/build/outputs/*-results/**/*.xml
            **/build/*-results/**/*.xml
